<%@ page import="entity.*" %>
<%@ page language="java" import="java.util.*" contentType="text/html; charset=utf-8"
    pageEncoding="utf-8" %>
<%
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
ArrayList feed = (ArrayList) request.getAttribute("feed");
ArrayList feedTop = (ArrayList) request.getAttribute("feedTop");
String avatar = (String) request.getAttribute("avatar");
String islogin = (String)request.getAttribute("login") == "ok" ? "ok" : "fail";
String isOk = (String)request.getAttribute("isOk") == "is" ? "is":"not";
System.out.println(islogin+isOk);
%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
<head>
<base href="<%=basePath%>">
<meta http-equiv="Content-Type" content="text/html; charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<meta name="description"content="Basic HTML5 App generated by MyEclipse Mobile Tools" />
 <!--引入Bootstrap-->
 <link href="<%= path %>/bootstrap3.3.7/css/bootstrap.css" rel="stylesheet" >
 <script type="text/javascript" src="<%= path %>/bootstrap3.3.7/js/bootstrap.js" ></script>
 <!--引入jquery-->
 <script type="text/javascript" src="<%= path %>/jquery-3.2.1.min.js"></script>
 <!--导入jQueryForm插件-->
 <script type="text/javascript" src="<%= path %>/jquery-form.js"></script>
 <!-- 引入外部css-->
 <link href="<%= path %>/css/feed.css" rel="stylesheet" >
 <!-- layer -->
 <script type="text/javascript" src="<%= path %>/layer/layer.js"></script>
 <!-- 进入vue 
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>-->
<title>feed</title>
<style>
</style>
<script type="text/javascript">
       $(document).ready(function(){

       	if(document.body.scrollWidth <700){
       		$("img.tubiao").hide();
       	}


		$("button.login").click(function() {
			/* Act on the event */
			layer.open({
                   type: 2,
                   title: '登陆',
                   shadeClose: true,
                   shade: 0.8,
                   area: ['400px', '480px'],
                   content: "<%= path%>/userPages/login.jsp",
                   success: function(layero,index)
                   {
                   	 var subm = layer.getChildFrame('#subm',index);
                   	 var form = layer.getChildFrame('form#loginF',index);
                   	 subm.click(function(event) {
                   		form.ajaxSubmit({
                   			url : "<%= path%>/login",
                   			type : "post",
                   			enctype : "application/x-www-form-urlencoded",
                   			dataType : "json",
                   			success : function(data){
                   				if(data.code == "success"){
                   					
                   					if(data.isOk == "is"){
                       					alert("登陆成功");
                       					layer.closeAll();
                       					var avatar = data.avatar==null ? "<%= path %>/images/defaultTouxiang.jpg": data.avatar ;
                       					$("img.touxiang1").attr("src",avatar);
                       					$("div#avatar").attr("class","touxiang");
                       					$("button#ask").attr("class","ask");
                   					}else if(data.isOk == "not"){
                   						alert("你已被封号，不能发布问题！");
                       					layer.closeAll();
                       					var avatar = data.avatar==null ? "<%= path %>/images/defaultTouxiang.jpg": data.avatar ;
                       					$("img.touxiang1").attr("src",avatar);
                       					$("div#avatar").attr("class","touxiang");
                   					}

                   				}else{
                   					layer.msg("登陆失败");
                   				}
                   			},
                   			fail:function(){
                   				alert("ksdfjskd");
                   			}
                   			
                   		})
                   	 	
                   	 });
                   }
               });


		
		});


		$("button.zhuce").click(function() {
			/* Act on the event */
			
			layer.open({
                   type: 2	,
                   title: '注册',
                   shadeClose: true,
                   shade: 0.8,
                   area: ['400px', '480px'],
                   content:  " <%= path %>/userPages/Register.jsp ",
                   success:function(layero,index)
                   {
                   	// layer.msg('注册成功')；
                   	 var subm = layer.getChildFrame('#submit',index);
                   	 var form = layer.getChildFrame('form#RegisterF',index);
                   	 subm.click(function(event) {
                   		form.ajaxSubmit({
                   			url : "<%= path%>/Register",
                   			type : "post",
                   			enctype : "application/x-www-form-urlencoded",
                   			dataType : "json",
                   			success : function(data){
                   				if(data.code == "success"){
                   					layer.msg("注册成功！");
                   					layer.closeAll();
                   				}
                   				else{
                   					layer.msg("注册失败！");
                   				}
                   			}
                   		});
                   	 });
                   }
                  
               });

		
		});


		$("button.ask").click(function() {
			/* Act on the event */
			layer.open({
                   type: 2,
                   title: '问题编辑',
                   shadeClose: true,
                   shade: 0.8,
                   area: ['700px', '350px'],
                   content: " <%= path %>/userPages/quesEdit.jsp " ,
                  success: function(layero,index)
                  {
                    	 var subm = layer.getChildFrame('#subm',index);
                    	 var form = layer.getChildFrame('form#quesEdit',index);
                    	 subm.click(function(event) {
                    		form.ajaxSubmit({
                    			url : " <%= path %>/quesEdit",
                    			type : "post",
                    			enctype : "application/x-www-form-urlencoded",
                    			dataType : "json",
                    			success : function(data){
                    				if(data != ""){
                    					layer.msg("发布成功！");
                    					
                    					layer.closeAll();

                    					var avatar = "<%= path %>/images/defaultTouxiang.jpg";
                    					var uid = data.uid ;
                    					var subTime = (data.subTime == "") ? "未知时间":data.subTime;
                    					var school = (data.school == "") ? "未知学校": data.school;
                    					
                  							
                    					$("div.rowList").prepend("<div class=\"row\" id=\"rowItem\">"
                    							+"<div class=\"container feed\" id=\""+data.qid+"\">"
            							+"<div class=\"row block\">"
            							+	"<div class=\"col-sm-2 block-avatar\">"
            							+		"<img class=\"avatar\" src="+ avatar +" alt=\"头像\" width=\"100\" height=\"100\"></img>"
            							+	"</div>"
            							+	"<div class=\"col-sm-10 block-content\">"
            							+		"<div class=\"row rightCol\">"
            							+			"<div class=\"col-xs-2 rightOner\">"
            							+				"<p style=\"color:black\"><b>"+uid+"</b></p>"
            							+			"</div>"
            							+			"<div class=\"col-xs-3 rightOner\">"
            							+				"<p>"+subTime+"</p>"
            							+			"</div>"
            							+			"<div class=\"col-xs-2 rightOner\">"
            							+				"<p>"+school+"</p>"
            							+			"</div>"
            							+		"</div>"
            							+		"<div class=\"row rightCol\">"
            							+			"<p>"+data.text+"</p>"
            							+		"</div>"
            							+		"<div class=\"row rightCol\">"
            							+			"<div class=\"col-xs-3\">"
            							+				"<div class=\"row\">"
            							+					"<div class=\"col-xs-2\">"
            							+						"<object data=\"icon/commit.svg\" width=\"300\" height=\"300\" type=\"image/svg+xml\" codebase=\"http://www.adobe.com/svg/viewer/imstall/\"></object>"
            							+					"</div>"
            							+					"<div class=\"col-xs-1\">"
            							+						"+"+data.follow
            							+					"</div>"
            							+				"</div>"
            							+			"</div>"
            							+			"<div class=\"col-xs-3\">"
            							+				"<div class=\"row\">"
            							+					"<div class=\"col-xs-2\">"
            							+						"<object data=\"icon/aixin.svg\" width=\"300\" height=\"300\" type=\"image/svg+xml\" codebase=\"http://www.adobe.com/svg/viewer/imstall/\"></object>"
            							+					"</div>"
            							+					"<div class=\"col-xs-1\">"
            							+						"+"+data.clickNum
            							+					"</div>"
            							+				"</div>"
            							+			"</div>"
            							+		"</div>"
            							+	"</div>"
            							+	"</div>"
            							+	"</div>"
            							+	"</div>");
                    					
                    				}
                    				else{
                    					layer.msg("发布失败！");
                    				}
                    			}
                    		});
                    	 });
                  }
               });

		
		});
		$("a#logout").click(function(){
			$.ajax({
				type:"GET",
				url:"<%= path %>/logout",
				dataType : "json",
				success : function(data){
					if(data.code == "success"){
						alert("退出成功");
						$("div#avatar").attr("class","touxiang display");
       					$("button#ask").attr("class","ask display");
					}else{
						alert("退出失败");
					}
				}
			});
		});
		
		$("img.searchk1").click(function(){
			var searchText = $("input.searchk").val();
			if(searchText == ""){
				alert("搜索框为空");
			}else{
				$.ajax({
					type:"POST",
					url: "<%= path%>/search",
					dataType : "json",
					contentType: "application/x-www-form-urlencoded; charset=UTF-8",
					data:{
						search : searchText
					},
					success:function(data){
						if(data != ""){
							//先隐藏
							$("div#rowItem").attr("class","row display");
							$("div#rowTopItem").attr("class","row display");
							//在遍历
							for(var i=0;i<data.length;i++){
	        					var avatar = "<%= path %>/images/defaultTouxiang.jpg";
	        					var uid = data[i].uid ;
	        					var subTime = (data[i].subTime == "") ? "未知时间":data[i].subTime;
	        					var school = (data[i].school == "") ? "未知学校": data[i].school;
	        					
	      							
	        					$("div.rowList").prepend("<div class=\"row\" id=\"rowItem\">"
	        							+"<div class=\"container feed\" id=\""+data.qid+"\">"
								+"<div class=\"row block\">"
								+	"<div class=\"col-sm-2 block-avatar\">"
								+		"<img class=\"avatar\" src="+ avatar +" alt=\"头像\" width=\"100\" height=\"100\"></img>"
								+	"</div>"
								+	"<div class=\"col-sm-10 block-content\">"
								+		"<div class=\"row rightCol\">"
								+			"<div class=\"col-xs-2 rightOner\">"
								+				"<p style=\"color:black\"><b>"+uid+"</b></p>"
								+			"</div>"
								+			"<div class=\"col-xs-3 rightOner\">"
								+				"<p>"+subTime+"</p>"
								+			"</div>"
								+			"<div class=\"col-xs-2 rightOner\">"
								+				"<p>"+school+"</p>"
								+			"</div>"
								+		"</div>"
								+		"<div class=\"row rightCol\">"
								+			"<p>"+data[i].text+"</p>"
								+		"</div>"
								+		"<div class=\"row rightCol\">"
								+			"<div class=\"col-xs-3\">"
								+				"<div class=\"row\">"
								+					"<div class=\"col-xs-2\">"
								+						"<object data=\"icon/commit.svg\" width=\"300\" height=\"300\" type=\"image/svg+xml\" codebase=\"http://www.adobe.com/svg/viewer/imstall/\"></object>"
								+					"</div>"
								+					"<div class=\"col-xs-1\">"
								+						"+"+data[i].follow
								+					"</div>"
								+				"</div>"
								+			"</div>"
								+			"<div class=\"col-xs-3\">"
								+				"<div class=\"row\">"
								+					"<div class=\"col-xs-2\">"
								+						"<object data=\"icon/aixin.svg\" width=\"300\" height=\"300\" type=\"image/svg+xml\" codebase=\"http://www.adobe.com/svg/viewer/imstall/\"></object>"
								+					"</div>"
								+					"<div class=\"col-xs-1\">"
								+						"+"+data[i].clickNum
								+					"</div>"
								+				"</div>"
								+			"</div>"
								+		"</div>"
								+	"</div>"
								+	"</div>"
								+	"</div>"
								+	"</div>");
							}

						}else{
							alert("无结果");
							window.location.href="<%= path%>/index";
						}
					}
				});
			}
		});
		
		$("img.cate1").click(function(){
				$.ajax({
					type:"POST",
					url: "<%= path%>/computer",
					dataType : "json",
					contentType: "application/x-www-form-urlencoded; charset=UTF-8",
					success:function(data){
						if(data == ""){
								alert("无结果");
								window.location.href="<%= path%>/index";
						}
						else{
							//先隐藏
							$("div#rowItem").attr("class","row display");
							$("div#rowTopItem").attr("class","row display");
							//在遍历
							for(var i=0;i<data.length;i++){
	        					var avatar = "<%= path %>/images/defaultTouxiang.jpg";
	        					var uid = data[i].uid ;
	        					var subTime = (data[i].subTime == "") ? "未知时间":data[i].subTime;
	        					var school = (data[i].school == "") ? "未知学校": data[i].school;
	        					
	      							
	        					$("div.rowList").prepend("<div class=\"row\" id=\"rowItem\">"
	        							+"<div class=\"container feed\" id=\""+data.qid+"\">"
								+"<div class=\"row block\">"
								+	"<div class=\"col-sm-2 block-avatar\">"
								+		"<img class=\"avatar\" src="+ avatar +" alt=\"头像\" width=\"100\" height=\"100\"></img>"
								+	"</div>"
								+	"<div class=\"col-sm-10 block-content\">"
								+		"<div class=\"row rightCol\">"
								+			"<div class=\"col-xs-2 rightOner\">"
								+				"<p style=\"color:black\"><b>"+uid+"</b></p>"
								+			"</div>"
								+			"<div class=\"col-xs-3 rightOner\">"
								+				"<p>"+subTime+"</p>"
								+			"</div>"
								+			"<div class=\"col-xs-2 rightOner\">"
								+				"<p>"+school+"</p>"
								+			"</div>"
								+		"</div>"
								+		"<div class=\"row rightCol\">"
								+			"<p>"+data[i].text+"</p>"
								+		"</div>"
								+		"<div class=\"row rightCol\">"
								+			"<div class=\"col-xs-3\">"
								+				"<div class=\"row\">"
								+					"<div class=\"col-xs-2\">"
								+						"<object data=\"icon/commit.svg\" width=\"300\" height=\"300\" type=\"image/svg+xml\" codebase=\"http://www.adobe.com/svg/viewer/imstall/\"></object>"
								+					"</div>"
								+					"<div class=\"col-xs-1\">"
								+						"+"+data[i].follow
								+					"</div>"
								+				"</div>"
								+			"</div>"
								+			"<div class=\"col-xs-3\">"
								+				"<div class=\"row\">"
								+					"<div class=\"col-xs-2\">"
								+						"<object data=\"icon/aixin.svg\" width=\"300\" height=\"300\" type=\"image/svg+xml\" codebase=\"http://www.adobe.com/svg/viewer/imstall/\"></object>"
								+					"</div>"
								+					"<div class=\"col-xs-1\">"
								+						"+"+data[i].clickNum
								+					"</div>"
								+				"</div>"
								+			"</div>"
								+		"</div>"
								+	"</div>"
								+	"</div>"
								+	"</div>"
								+	"</div>");
							}

						}
					}
				});
			
		});
		
		$("img.cate2").click(function(){
			$.ajax({
				type:"POST",
				url: "<%= path%>/renwen",
				dataType : "json",
				contentType: "application/x-www-form-urlencoded; charset=UTF-8",
				success:function(data){
					if(data == ""){
							alert("无结果");
							window.location.href="<%= path%>/index";
					}
					else{
						//先隐藏
						$("div#rowItem").attr("class","row display");
						$("div#rowTopItem").attr("class","row display");
						//在遍历
						for(var i=0;i<data.length;i++){
        					var avatar = "<%= path %>/images/defaultTouxiang.jpg";
        					var uid = data[i].uid ;
        					var subTime = (data[i].subTime == "") ? "未知时间":data[i].subTime;
        					var school = (data[i].school == "") ? "未知学校": data[i].school;
        					
      							
        					$("div.rowList").prepend("<div class=\"row\" id=\"rowItem\">"
        							+"<div class=\"container feed\" id=\""+data.qid+"\">"
							+"<div class=\"row block\">"
							+	"<div class=\"col-sm-2 block-avatar\">"
							+		"<img class=\"avatar\" src="+ avatar +" alt=\"头像\" width=\"100\" height=\"100\"></img>"
							+	"</div>"
							+	"<div class=\"col-sm-10 block-content\">"
							+		"<div class=\"row rightCol\">"
							+			"<div class=\"col-xs-2 rightOner\">"
							+				"<p style=\"color:black\"><b>"+uid+"</b></p>"
							+			"</div>"
							+			"<div class=\"col-xs-3 rightOner\">"
							+				"<p>"+subTime+"</p>"
							+			"</div>"
							+			"<div class=\"col-xs-2 rightOner\">"
							+				"<p>"+school+"</p>"
							+			"</div>"
							+		"</div>"
							+		"<div class=\"row rightCol\">"
							+			"<p>"+data[i].text+"</p>"
							+		"</div>"
							+		"<div class=\"row rightCol\">"
							+			"<div class=\"col-xs-3\">"
							+				"<div class=\"row\">"
							+					"<div class=\"col-xs-2\">"
							+						"<object data=\"icon/commit.svg\" width=\"300\" height=\"300\" type=\"image/svg+xml\" codebase=\"http://www.adobe.com/svg/viewer/imstall/\"></object>"
							+					"</div>"
							+					"<div class=\"col-xs-1\">"
							+						"+"+data[i].follow
							+					"</div>"
							+				"</div>"
							+			"</div>"
							+			"<div class=\"col-xs-3\">"
							+				"<div class=\"row\">"
							+					"<div class=\"col-xs-2\">"
							+						"<object data=\"icon/aixin.svg\" width=\"300\" height=\"300\" type=\"image/svg+xml\" codebase=\"http://www.adobe.com/svg/viewer/imstall/\"></object>"
							+					"</div>"
							+					"<div class=\"col-xs-1\">"
							+						"+"+data[i].clickNum
							+					"</div>"
							+				"</div>"
							+			"</div>"
							+		"</div>"
							+	"</div>"
							+	"</div>"
							+	"</div>"
							+	"</div>");
						}

					}
				}
			});
		
	});
		
		$("img.cate3").click(function(){
			$.ajax({
				type:"POST",
				url: "<%= path%>/others",
				dataType : "json",
				contentType: "application/x-www-form-urlencoded; charset=UTF-8",
				success:function(data){
					if(data == ""){
							alert("无结果");
							window.location.href="<%= path%>/index";
					}
					else{
						//先隐藏
						$("div#rowItem").attr("class","row display");
						$("div#rowTopItem").attr("class","row display");
						//在遍历
						for(var i=0;i<data.length;i++){
        					var avatar = "<%= path %>/images/defaultTouxiang.jpg";
        					var uid = data[i].uid ;
        					var subTime = (data[i].subTime == "") ? "未知时间":data[i].subTime;
        					var school = (data[i].school == "") ? "未知学校": data[i].school;
        					
      							
        					$("div.rowList").prepend("<div class=\"row\" id=\"rowItem\">"
        							+"<div class=\"container feed\" id=\""+data.qid+"\">"
							+"<div class=\"row block\">"
							+	"<div class=\"col-sm-2 block-avatar\">"
							+		"<img class=\"avatar\" src="+ avatar +" alt=\"头像\" width=\"100\" height=\"100\"></img>"
							+	"</div>"
							+	"<div class=\"col-sm-10 block-content\">"
							+		"<div class=\"row rightCol\">"
							+			"<div class=\"col-xs-2 rightOner\">"
							+				"<p style=\"color:black\"><b>"+uid+"</b></p>"
							+			"</div>"
							+			"<div class=\"col-xs-3 rightOner\">"
							+				"<p>"+subTime+"</p>"
							+			"</div>"
							+			"<div class=\"col-xs-2 rightOner\">"
							+				"<p>"+school+"</p>"
							+			"</div>"
							+		"</div>"
							+		"<div class=\"row rightCol\">"
							+			"<p>"+data[i].text+"</p>"
							+		"</div>"
							+		"<div class=\"row rightCol\">"
							+			"<div class=\"col-xs-3\">"
							+				"<div class=\"row\">"
							+					"<div class=\"col-xs-2\">"
							+						"<object data=\"icon/commit.svg\" width=\"300\" height=\"300\" type=\"image/svg+xml\" codebase=\"http://www.adobe.com/svg/viewer/imstall/\"></object>"
							+					"</div>"
							+					"<div class=\"col-xs-1\">"
							+						"+"+data[i].follow
							+					"</div>"
							+				"</div>"
							+			"</div>"
							+			"<div class=\"col-xs-3\">"
							+				"<div class=\"row\">"
							+					"<div class=\"col-xs-2\">"
							+						"<object data=\"icon/aixin.svg\" width=\"300\" height=\"300\" type=\"image/svg+xml\" codebase=\"http://www.adobe.com/svg/viewer/imstall/\"></object>"
							+					"</div>"
							+					"<div class=\"col-xs-1\">"
							+						"+"+data[i].clickNum
							+					"</div>"
							+				"</div>"
							+			"</div>"
							+		"</div>"
							+	"</div>"
							+	"</div>"
							+	"</div>"
							+	"</div>");
						}

					}
				}
			});
		
	});
		
		$("img.cate4").click(function(){
			$.ajax({
				type:"POST",
				url: "<%= path%>/all",
				dataType : "json",
				contentType: "application/x-www-form-urlencoded; charset=UTF-8",
				success:function(data){
					if(data == ""){
						
							window.location.href="<%= path%>/index";
					}
					else{
						//先隐藏
						$("div#rowItem").attr("class","row display");
						$("div#rowTopItem").attr("class","row display");
						//在遍历
						for(var i=0;i<data.length;i++){
        					var avatar = "<%= path %>/images/defaultTouxiang.jpg";
        					var uid = data[i].uid ;
        					var subTime = (data[i].subTime == "") ? "未知时间":data[i].subTime;
        					var school = (data[i].school == "") ? "未知学校": data[i].school;
        					
      							
        					$("div.rowList").prepend("<div class=\"row\" id=\"rowItem\">"
        							+"<div class=\"container feed\" id=\""+data.qid+"\">"
							+"<div class=\"row block\">"
							+	"<div class=\"col-sm-2 block-avatar\">"
							+		"<img class=\"avatar\" src="+ avatar +" alt=\"头像\" width=\"100\" height=\"100\"></img>"
							+	"</div>"
							+	"<div class=\"col-sm-10 block-content\">"
							+		"<div class=\"row rightCol\">"
							+			"<div class=\"col-xs-2 rightOner\">"
							+				"<p style=\"color:black\"><b>"+uid+"</b></p>"
							+			"</div>"
							+			"<div class=\"col-xs-3 rightOner\">"
							+				"<p>"+subTime+"</p>"
							+			"</div>"
							+			"<div class=\"col-xs-2 rightOner\">"
							+				"<p>"+school+"</p>"
							+			"</div>"
							+		"</div>"
							+		"<div class=\"row rightCol\">"
							+			"<p>"+data[i].text+"</p>"
							+		"</div>"
							+		"<div class=\"row rightCol\">"
							+			"<div class=\"col-xs-3\">"
							+				"<div class=\"row\">"
							+					"<div class=\"col-xs-2\">"
							+						"<object data=\"icon/commit.svg\" width=\"300\" height=\"300\" type=\"image/svg+xml\" codebase=\"http://www.adobe.com/svg/viewer/imstall/\"></object>"
							+					"</div>"
							+					"<div class=\"col-xs-1\">"
							+						"+"+data[i].follow
							+					"</div>"
							+				"</div>"
							+			"</div>"
							+			"<div class=\"col-xs-3\">"
							+				"<div class=\"row\">"
							+					"<div class=\"col-xs-2\">"
							+						"<object data=\"icon/aixin.svg\" width=\"300\" height=\"300\" type=\"image/svg+xml\" codebase=\"http://www.adobe.com/svg/viewer/imstall/\"></object>"
							+					"</div>"
							+					"<div class=\"col-xs-1\">"
							+						"+"+data[i].clickNum
							+					"</div>"
							+				"</div>"
							+			"</div>"
							+		"</div>"
							+	"</div>"
							+	"</div>"
							+	"</div>"
							+	"</div>");
						}

					}
				}
			});
		
	});
		
		$("div.feed").click(function(){
			var qid = $(this).attr("id");
		
			window.location.href = "<%= path %>/userPages/problemDetails.jsp?q_id=" + qid ;
		});


});
</script>
</head>
<body style="background-image: url(<%= path %>/images/back.jpg)">
<div id="vue">
	<div class="header" id="header">
		<nav class="navbar" role="navigation" style="height: 105px">
		   <div class="navbar-header" >
		      <img  class="tubiao" src="<%= path %>/images/biao.jpg" width="100" height="100" alt="图标">
		   </div>
		   <!--    <div class="navbar-form navbar-left">
		         <div style="margin-top:2em;" class="form-group"> -->
		         <div class="group">
		            <input class="searchk" type="text" class="form-control" placeholder="Search" />
					<img class="searchk1" src="images/search.png" alt="搜索" width="30" height="30"/>
					<button class="ask <%= islogin == "ok" && isOk == "is" ? "":"display" %>"  id="ask">求问</button>
					<button class="login">登录</button>
					<button class="zhuce">注册</button>
				</div>
 
		      <div id="avatar" class="touxiang <%= islogin== "fail" ? "display":"" %>">
					<div class="dropdown">
  						<img class="touxiang1" src="<%= path %>/images/defaultTouxiang.jpg" width="50" height="50" alt="头像">
	  					<div class="dropdown-content">
	    				<a href="<%= path%>/toPerson">个人主页</a>
	    				<a id="logout">退出登录</a>
	  					</div>
					</div>

			  </div>
		</nav>
	</div>
		<div class="container body" id="content">
			<div class="row top" style="width:200px; ">
				<h3>最新问题</h3>
			</div>
			<img class="cate4" src="images/search1.png" alt="显示全部" width="30" height="30" style="width:80px;position:absolute;top:15%;left:30%;background-color:white;border-radius:10%;"/>
			<img class="cate1" src="images/search2.png" alt="计算机" width="30" height="30" style="width:80px;position:absolute;top:15%;left:37%;background-color:white;border-radius:10%;"/>
			<img class="cate2" src="images/search3.png" alt="人文" width="30" height="30" style="width:80px;position:absolute;top:15%;left:44%;background-color:white;border-radius:10%;"/>
			<img class="cate3" src="images/search4.png" alt="其他" width="30" height="30" style="width:80px;position:absolute;top:15%;left:51%;background-color:white;border-radius:10%;"/>

			<div class="rowTopList">
							<%
				for(int i = 0 ;i<feedTop.size();i++){
					UserQuesBean questop = (UserQuesBean)feedTop.get(i);
			%>
					<div class="row" id="rowTopItem" >
						<div class="container feed" id="<%= questop.getQid() %>">
							<div class="row block" style="background:#FFF7D4;">
								<div class="col-sm-2 block-avatar" >
									<img class="avatar" src="<%= path %>/images/defaultTouxiang.jpg" alt="头像" width="100" height="100"></img>
								</div>
								<div class="col-sm-10 block-content">
									<div class="row rightCol">
										<div class="col-xs-2 rightOner">
											<p style="color:black"><b><%= questop.getAccount() %></b></p>
										</div>
										<div class="col-xs-3 rightOner">
											<p><%= questop.getSubTime() %></p>
										</div>
										<div class="col-xs-2 rightOner">
											<p><%= questop.getSchool()==null ? "未知学校":questop.getSchool() %></p>
										</div>
									</div>
									<div class="row rightCol">
										<p><%= questop.getText()==null ? "未知内容":questop.getText()  %></p>
									</div>
									<div class="row rightCol">
										<div class="col-xs-3">
											<div class="row">
												<div class="col-xs-2">
													<object data="icon/commit.svg" width="300" height="300" type="image/svg+xml" codebase="http://www.adobe.com/svg/viewer/imstall/"></object>
												</div>
												<div class="col-xs-1">
													+<%= questop.getFollow() %>
												</div>
											</div>
										</div>
										<div class="col-xs-3">
											<div class="row">
												<div class="col-xs-2">
													<object data="icon/aixin.svg" width="300" height="300" type="image/svg+xml" codebase="http://www.adobe.com/svg/viewer/imstall/"></object>
												</div>
												<div class="col-xs-1">
													+<%= questop.getClickNum() %>
												</div>
											</div>
										</div>
										<div class="col-xs-3">
											<div class="row">
												<div class="col-xs-2">
													<object data="icon/jubao.svg" width="300" height="300" type="image/svg+xml" codebase="http://www.adobe.com/svg/viewer/imstall/"></object>
												</div>
												<div class="col-xs-9">
													<%= questop.getCategory() %>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="topImg">
									<img src="<%= path %>/images/top.png" height="70" width="70" />
								</div>
							</div>
						</div>
					</div>
					<%  } %>
			</div>
			 <div class="rowList">
			<%
				for(int i = 0 ;i<feed.size();i++){
					UserQuesBean ques = (UserQuesBean)feed.get(i);
			%>
					<div class="row" id="rowItem">
						<div class="container feed" id="<%= ques.getQid() %>">
							<div class="row block">
								<div class="col-sm-2 block-avatar">
									<img class="avatar" src="<%= path %>/images/defaultTouxiang.jpg" alt="头像" width="100" height="100"></img>
								</div>
								<div class="col-sm-10 block-content">
									<div class="row rightCol">
										<div class="col-xs-2 rightOner">
											<p style="color:black"><b><%= ques.getAccount() %></b></p>
										</div>
										<div class="col-xs-3 rightOner">
											<p><%= ques.getSubTime() %></p>
										</div>
										<div class="col-xs-2 rightOner">
											<p><%= ques.getSchool()==null ? "未知学校":ques.getSchool() %></p>
										</div>
									</div>
									<div class="row rightCol">
										<p><%= ques.getText()==null ? "未知内容":ques.getText()  %></p>
									</div>
									<div class="row rightCol">
										<div class="col-xs-3">
											<div class="row">
												<div class="col-xs-2">
													<object data="icon/commit.svg" width="300" height="300" type="image/svg+xml" codebase="http://www.adobe.com/svg/viewer/imstall/"></object>
												</div>
												<div class="col-xs-1">
													+<%= ques.getFollow() %>
												</div>
											</div>
										</div>
										<div class="col-xs-3">
											<div class="row">
												<div class="col-xs-2">
													<object data="icon/aixin.svg" width="300" height="300" type="image/svg+xml" codebase="http://www.adobe.com/svg/viewer/imstall/"></object>
												</div>
												<div class="col-xs-1">
													+<%= ques.getClickNum() %>
												</div>
											</div>
										</div>
										<div class="col-xs-3">
											<div class="row">
												<div class="col-xs-2">
													<object data="icon/jubao.svg" width="300" height="300" type="image/svg+xml" codebase="http://www.adobe.com/svg/viewer/imstall/"></object>
												</div>
												<div class="col-xs-9">
													<%= ques.getCategory() %>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<%  } %>
				</div>
			
		</div>
</div>

</body>
</html>