<%@ page import="entity.*" %>
<%@ page import="utils.*" %>
<%@ page language="java" contentType="text/html; charset=utf-8" import="java.util.*"
    pageEncoding="utf-8"%>
<%@ page import="java.sql.*" %>
<!DOCTYPE html>


<%
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
String strId=request.getParameter("q_id");//得到上一个界面的q_id
int u_id = -1;
HttpSession session1 = request.getSession();
if(session1 != null){
	if(session1.getAttribute("uid")!=null){
		u_id = (int) session1.getAttribute("uid");
	}
}
//HttpSession session1=request.getSession();
//int id2 =(int) session1.getAttribute("u_id");//得到session的值并转化成整型
int id=Integer.parseInt(strId);
//int id=1;


Class.forName(DBConn.getDRI());
Connection conn = DriverManager.getConnection(DBConn.getURL(), DBConn.getUsr(), DBConn.getPWD());


Statement stmt=conn.createStatement();
Statement stmt1=conn.createStatement();
Statement stmt2=conn.createStatement();
Statement stmt3=conn.createStatement();
Statement stmt4=conn.createStatement();
Statement stmt5=conn.createStatement();
//ResultSet rs=stmt.executeQuery("select * from article where id='"+id+"'");

ResultSet rs=stmt.executeQuery("select * from qiuwen_question where q_id="+id);//问题
ResultSet rs1=stmt1.executeQuery("select * from qiuwen_userques where q_id="+id);//提问题的用户和时间
if(rs1.next()){
	ResultSet rs2=stmt2.executeQuery("select * from qiuwen_user where usr_id="+rs1.getInt("u_id"));//提问题的用户


		

%>
<html>

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
	<meta name="description" content="Basic HTML5 App generated by MyEclipse Mobile Tools" />
	<!--引入Bootstrap-->
	<link href="../bootstrap3.3.7/css/bootstrap.css" rel="stylesheet">
	<script type="text/javascript" src="../bootstrap3.3.7/js/bootstrap.js"></script>
	<!--引入jquery-->
	<script type="text/javascript" src="../jquery-3.2.1.min.js"></script>
	<!-- 引入外部css-->
	<link href="../css/problemDetails.css" rel="stylesheet">
	 <!-- layer -->
 <script type="text/javascript" src="../layer/layer.js"></script>
	<title>problemDetails</title>
	<style>
	</style>
	<script type="text/javascript">
		 $(document).ready(function(){

       	$("button#answer").click(function(){
       		window.location.href="questionEdit.html"; 
       	});

		$("button.login").click(function() {
			/* Act on the event */
			layer.open({
                   type: 2,
                   title: '登陆',
                   shadeClose: true,
                   shade: 0.8,
                   area: ['400px', '480px'],
                   content: 'login.html' ,
                  // success: function(layero,index)
                  // {
                  // 	 var subm = layer.getChildFrame('#subm',index);
                  // 	 subm.click(function(event) {
                  // 	 layer.closeAll();
                  // 	 });
                  // }
               });


		
		});


		$("button.zhuce").click(function() {
			/* Act on the event */
			layer.open({
                   type: 2,
                   title: '注册',
                   shadeClose: true,
                   shade: 0.8,
                   area: ['400px', '480px'],
                   content: 'sign.html' ,
                   success:function(layero,index)
                   {
                   	// layer.msg('注册成功')；
                   }
                  
               });

		
		});


		$("button.ask").click(function() {
			/* Act on the event */
			layer.open({
                   type: 2,
                   title: '问题编辑',
                   shadeClose: true,
                   shade: 0.8,
                   area: ['700px', '350px'],
                   content: 'edit.html' ,
                  success: function(layero,index)
                  {


                  		// layer.msg('提交成功')
                  }
               });

		
		});
});
	</script>
</head>

<body style="background-image: url(../images/back.jpg)">


<% 
  		//ArrayList answers = (ArrayList) request.getAttribute("qiuwen_question_answer");
	while(rs.next()&rs2.next()) {
  	%>
	<div class="header" id="header">
		<nav class="navbar" role="navigation" style="height: 105px">
		   <div class="navbar-header" >
		      <img  class="tubiao" src="../images/biao.jpg" width="100" height="100" alt="图标">
		   </div>
		  
		</nav>
	</div>

	<div class="container body">
		<div class="row top">
		</div>
		<div class="row">
			<div class="container problemDetails">
				<div class="row block">
					<div class="col-sm-2 block-avatar">
						<img class="avatar" src="../images/defaultTouxiang.jpg" alt="头像" width="100" height="100"/>
					</div>
					<div class="col-sm-10 block-content">
						<div class="row rightCol">
							<div class="col-xs-9 rightOner">
								<p style="color:black">
									<b><%=rs2.getString("usr_account") %></b>
								</p>
							</div>
							<div class="col-xs-3 rightOner">
								<p><%=rs.getDate("sub_time") %></p>
							</div>
							<div class="col-xs-2 rightOner">
								<p><%=rs2.getString("school") %></p>
							</div>
						</div>
						<div class="row rightCol">
							<p><%=rs.getString("q_text") %> </p>
						</div>
									<div class="row rightCol">
										<div class="col-xs-2">
											<div class="row">
												<div class="col-xs-2">
													<object data="icon/commit.svg" width="300" height="300" type="image/svg+xml" codebase="http://www.adobe.com/svg/viewer/imstall/"></object>
												</div>
												<div class="col-xs-1">
													+<%=rs.getInt("follow")%>
												</div>
											</div>
										</div>
										<div class="col-xs-2">
											<div class="row">
												<div class="col-xs-2">
													<object data="icon/aixin.svg" width="300" height="300" type="image/svg+xml" codebase="http://www.adobe.com/svg/viewer/imstall/"></object>
												</div>
												<div class="col-xs-1">
													+<%=rs.getInt("click_num") %>
												</div>
											</div>
										</div>
										<div class="col-xs-2">
											<div class="row">
												<div class="col-xs-2">
													<object data="icon/jubao.svg" width="300" height="300" type="image/svg+xml" codebase="http://www.adobe.com/svg/viewer/imstall/"></object>
												</div>
												<div class="col-xs-9">
											    <%=rs.getString("category") %>
												</div>
											</div>
										</div>
										<div class="col-xs-6">
											<a href="<%=basePath%>/userPages/questionEdit.jsp?q_id=<%=rs.getInt("q_id")%>"><button id="answer" class="btn btn-info btn-sm" style="<%= u_id == -1 ? "display:none":"" %>"> 我要回答</button>	</a>
										</div>
									</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<%
		ResultSet rs3=stmt3.executeQuery("select * from qiuwen_quesanswer where q_id="+id);//回答
		while(rs3.next()){
			ResultSet rs4=stmt4.executeQuery("select * from qiuwen_user where usr_id="+rs3.getInt("u_id"));//回答的用户
			if(rs4.next()){
			%>
	<div class="container body">
		<div class="row">
			<div class="container problemDetails">
				<div class="row block2">
					<div class="col-md-2 block-avatar">
						<img class="avatar" src="../images/profile.jpg" alt="头像" width="100" height="100"/>
					</div>
					<div class="col-md-10 block-content">
						<div class="row center col-md-10 block-content">
							<div>
								<div style="float:left">
									<p style="color:black"><%=rs4.getString("usr_account") %>：</p>
								</div>
								<div style="float:left">
									<p> <%=rs3.getDate("ans_time") %> <%=rs4.getString("school") %></p>
								</div>
							</div>


						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row col2 block3 ">
				<p><%=rs3.getString("a_text") %>
				</p>
		</div>
		<div class="row">
			<div class="container problemDetails">
				<div id="footer" style="text-align:right;padding-right: 2%">
					
					<div class="lineFront">
						<hr>
					</div>
				</div>
			</div>
		</div>
	</div>

<%				}
			}
		}
	}
%>	
</body>

</html>